////////////////////////////////////////////////////////////////////////////////////////////////////
//
//
//
////////////////////////////////////////////////////////////////////////////////////////////////////

#define I8061_INVALID_INSTRUCTION                                                                  \
    INSTRUCTION_INST( "********<invalid instruction>********", 0x00, 0, flds_intrinsic, TGT_INVALID )

// index: opcode - 0x4c
#define I8061_PREFIXED_INSTRUCTION_SET                                                                                                                   \
    INSTRUCTION_INST( "mul",   0xfe4c0000, flds_pre_3op_waopl_direct,        ADDRMD_3OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "mul",   0xfe4d0000, flds_pre_3op_waopl_immediate,     ADDRMD_3OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "mul",   0xfe4e0000, flds_pre_3op_waopl_indirect,      ADDRMD_3OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "mul",   0xfe4e0000, flds_pre_3op_waopl_indirect_auto_inc, ADDRMD_3OP_INDIRECT_AUTO_INC, TGT_READ ),                               \
    INSTRUCTION_INST( "mul",   0xfe4f0000, flds_pre_3op_waopl_indexed,       ADDRMD_3OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "mul",   0xfe4f0000, flds_pre_3op_waopl_direct_long,   ADDRMD_3OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "mul",   0xfe4f0000, flds_pre_3op_waopl_indexed_long,  ADDRMD_3OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( NULL,    0xfe500000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe510000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe520000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe530000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe540000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe550000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe560000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe570000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe580000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe590000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe5a0000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe5b0000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "mulb",  0xfe5c0000, flds_pre_3op_baopw_direct,        ADDRMD_3OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "mulb",  0xfe5d0000, flds_pre_3op_baopw_immediate,     ADDRMD_3OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "mulb",  0xfe5e0000, flds_pre_3op_baopw_indirect,      ADDRMD_3OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "mulb",  0xfe5e0000, flds_pre_3op_baopw_indirect_auto_inc, ADDRMD_3OP_INDIRECT_AUTO_INC, TGT_READ ),                               \
    INSTRUCTION_INST( "mulb",  0xfe5f0000, flds_pre_3op_baopw_indexed,       ADDRMD_3OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "mulb",  0xfe5f0000, flds_pre_3op_baopw_direct_long,   ADDRMD_3OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "mulb",  0xfe5f0000, flds_pre_3op_baopw_indexed_long,  ADDRMD_3OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( NULL,    0xfe600000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe610000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe620000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe630000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe640000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe650000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe660000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe670000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe680000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe690000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe6a0000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe6b0000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "mul",   0xfe6c0000, flds_pre_2op_waopl_direct,        ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "mul",   0xfe6d0000, flds_pre_2op_waopl_immediate,     ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "mul",   0xfe6e0000, flds_pre_2op_waopl_indirect,      ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "mul",   0xfe6e0000, flds_pre_3op_waopl_indirect_auto_inc, ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                               \
    INSTRUCTION_INST( "mul",   0xfe6f0000, flds_pre_2op_waopl_indexed,       ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "mul",   0xfe6f0000, flds_pre_2op_waopl_direct_long,   ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "mul",   0xfe6f0000, flds_pre_2op_waopl_indexed_long,  ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( NULL,    0xfe700000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe710000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe720000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe730000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe740000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe750000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe760000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe770000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe780000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe790000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe7a0000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe7b0000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "mulb",  0xfe7c0000, flds_pre_2op_baopw_direct,        ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "mulb",  0xfe7d0000, flds_pre_2op_baopw_immediate,     ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "mulb",  0xfe7e0000, flds_pre_2op_baopw_indirect,      ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "mulb",  0xfe7e0000, flds_pre_3op_baopw_indirect_auto_inc, ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                               \
    INSTRUCTION_INST( "mulb",  0xfe7f0000, flds_pre_2op_baopw_indexed,       ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "mulb",  0xfe7f0000, flds_pre_2op_baopw_direct_long,   ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "mulb",  0xfe7f0000, flds_pre_2op_baopw_indexed_long,  ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( NULL,    0xfe800000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe810000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe820000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe830000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe840000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe850000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe860000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe870000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe880000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe890000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe8a0000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe8b0000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "div",   0xfe8c0000, flds_pre_2op_waopl_direct,        ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "div",   0xfe8d0000, flds_pre_2op_waopl_immediate,     ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "div",   0xfe8e0000, flds_pre_2op_waopl_indirect,      ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "div",   0xfe8e0000, flds_pre_3op_waopl_indirect_auto_inc, ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                               \
    INSTRUCTION_INST( "div",   0xfe8f0000, flds_pre_2op_waopl_indexed,       ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "div",   0xfe8f0000, flds_pre_2op_waopl_direct_long,   ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "div",   0xfe8f0000, flds_pre_2op_waopl_indexed_long,  ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( NULL,    0xfe900000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe910000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe920000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe930000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe940000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe950000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe960000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe970000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe980000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe990000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe9a0000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe9b0000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "divb",  0xfe9c0000, flds_pre_2op_baopw_direct,        ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "divb",  0xfe9d0000, flds_pre_2op_baopw_immediate,     ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "divb",  0xfe9e0000, flds_pre_2op_baopw_indirect,      ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "divb",  0xfe9e0000, flds_pre_3op_baopw_indirect_auto_inc, ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                               \
    INSTRUCTION_INST( "divb",  0xfe9f0000, flds_pre_2op_baopw_indexed,       ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "divb",  0xfe9f0000, flds_pre_2op_baopw_direct_long,   ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "divb",  0xfe9f0000, flds_pre_2op_baopw_indexed_long,  ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \


#define I8061_INSTRUCTION_SET                                                                                                                            \
    INSTRUCTION_INST( "skip",  0x00000000, flds_bytereg,                     ADDRMD_1OP_DIRECT_LONG,       0 ),                                          \
    INSTRUCTION_INST( "clr",   0x01000000, flds_wordreg,                     ADDRMD_1OP_DIRECT_LONG,       0 ),                                          \
    INSTRUCTION_INST( "not",   0x02000000, flds_wordreg,                     ADDRMD_1OP_DIRECT_LONG,       0 ),                                          \
    INSTRUCTION_INST( "neg",   0x03000000, flds_wordreg,                     ADDRMD_1OP_DIRECT_LONG,       0 ),                                          \
    INSTRUCTION_INST( NULL,    0x04000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "dec",   0x05000000, flds_wordreg,                     ADDRMD_1OP_DIRECT_LONG,       0 ),                                          \
    INSTRUCTION_INST( "ext",   0x06000000, flds_longreg,                     ADDRMD_1OP_DIRECT_LONG,       0 ),                                          \
    INSTRUCTION_INST( "inc",   0x07000000, flds_wordreg,                     ADDRMD_1OP_DIRECT_LONG,       0 ),                                          \
    INSTRUCTION_INST( "shr",   0x08000000, flds_wordshft,                    ADDRMD_SHIFTS,                0 ),                                          \
    INSTRUCTION_INST( "shl",   0x09000000, flds_wordshft,                    ADDRMD_SHIFTS,                0 ),                                          \
    INSTRUCTION_INST( "shra",  0x0a000000, flds_wordshft,                    ADDRMD_SHIFTS,                0 ),                                          \
    INSTRUCTION_INST( NULL,    0x0b000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "shrl",  0x0c000000, flds_longshft,                    ADDRMD_SHIFTS,                0 ),                                          \
    INSTRUCTION_INST( "shll",  0x0d000000, flds_longshft,                    ADDRMD_SHIFTS,                0 ),                                          \
    INSTRUCTION_INST( "shral", 0x0e000000, flds_longshft,                    ADDRMD_SHIFTS,                0 ),                                          \
    INSTRUCTION_INST( "norml", 0x0f000000, flds_norml,                       ADDRMD_2OP_DIRECT_LONG,       0 ),                                          \
    INSTRUCTION_INST( NULL,    0x10000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "clrb",  0x11000000, flds_bytereg,                     ADDRMD_1OP_DIRECT_LONG,       0 ),                                          \
    INSTRUCTION_INST( "notb",  0x12000000, flds_bytereg,                     ADDRMD_1OP_DIRECT_LONG,       0 ),                                          \
    INSTRUCTION_INST( "negb",  0x13000000, flds_bytereg,                     ADDRMD_1OP_DIRECT_LONG,       0 ),                                          \
    INSTRUCTION_INST( NULL,    0x14000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "decb",  0x15000000, flds_bytereg,                     ADDRMD_1OP_DIRECT_LONG,       0 ),                                          \
    INSTRUCTION_INST( "extb",  0x16000000, flds_wordreg,                     ADDRMD_1OP_DIRECT_LONG,       0 ),                                          \
    INSTRUCTION_INST( "incb",  0x17000000, flds_bytereg,                     ADDRMD_1OP_DIRECT_LONG,       0 ),                                          \
    INSTRUCTION_INST( "shrb",  0x18000000, flds_byteshft,                    ADDRMD_SHIFTS,                0 ),                                          \
    INSTRUCTION_INST( "shlb",  0x19000000, flds_byteshft,                    ADDRMD_SHIFTS,                0 ),                                          \
    INSTRUCTION_INST( "shrab", 0x1a000000, flds_byteshft,                    ADDRMD_SHIFTS,                0 ),                                          \
    INSTRUCTION_INST( NULL,    0x1b000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0x1c000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0x1d000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0x1e000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0x1f000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "sjmp",  0x20000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_BARRIER ), \
    INSTRUCTION_INST( "sjmp",  0x21000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_BARRIER ), \
    INSTRUCTION_INST( "sjmp",  0x22000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_BARRIER ), \
    INSTRUCTION_INST( "sjmp",  0x23000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_BARRIER ), \
    INSTRUCTION_INST( "sjmp",  0x24000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_BARRIER ), \
    INSTRUCTION_INST( "sjmp",  0x25000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_BARRIER ), \
    INSTRUCTION_INST( "sjmp",  0x26000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_BARRIER ), \
    INSTRUCTION_INST( "sjmp",  0x27000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_BARRIER ), \
    INSTRUCTION_INST( "scall", 0x28000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_CALL ),    \
    INSTRUCTION_INST( "scall", 0x29000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_CALL ),    \
    INSTRUCTION_INST( "scall", 0x2a000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_CALL ),    \
    INSTRUCTION_INST( "scall", 0x2b000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_CALL ),    \
    INSTRUCTION_INST( "scall", 0x2c000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_CALL ),    \
    INSTRUCTION_INST( "scall", 0x2d000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_CALL ),    \
    INSTRUCTION_INST( "scall", 0x2e000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_CALL ),    \
    INSTRUCTION_INST( "scall", 0x2f000000, flds_scall_sjmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_CALL ),    \
    INSTRUCTION_INST( "jbc",   0x30000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbc",   0x31000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbc",   0x32000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbc",   0x33000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbc",   0x34000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbc",   0x35000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbc",   0x36000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbc",   0x37000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbs",   0x38000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbs",   0x39000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbs",   0x3a000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbs",   0x3b000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbs",   0x3c000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbs",   0x3d000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbs",   0x3e000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jbs",   0x3f000000, flds_jbc_jbs,                     ADDRMD_3OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "and",   0x40000000, flds_3op_waop_direct,             ADDRMD_3OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "and",   0x41000000, flds_3op_waop_immediate,          ADDRMD_3OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "and",   0x42000000, flds_3op_waop_indirect,           ADDRMD_3OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "and",   0x42000000, flds_3op_waop_indirect_auto_inc,  ADDRMD_3OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "and",   0x43000000, flds_3op_waop_indexed,            ADDRMD_3OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "and",   0x43000000, flds_3op_waop_direct_long,        ADDRMD_3OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "and",   0x43000000, flds_3op_waop_indexed_long,       ADDRMD_3OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "add",   0x44000000, flds_3op_waop_direct,             ADDRMD_3OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "add",   0x45000000, flds_3op_waop_immediate,          ADDRMD_3OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "add",   0x46000000, flds_3op_waop_indirect,           ADDRMD_3OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "add",   0x46000000, flds_3op_waop_indirect_auto_inc,  ADDRMD_3OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "add",   0x47000000, flds_3op_waop_indexed,            ADDRMD_3OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "add",   0x47000000, flds_3op_waop_direct_long,        ADDRMD_3OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "add",   0x47000000, flds_3op_waop_indexed_long,       ADDRMD_3OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "sub",   0x48000000, flds_3op_waop_direct,             ADDRMD_3OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "sub",   0x49000000, flds_3op_waop_immediate,          ADDRMD_3OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "sub",   0x4a000000, flds_3op_waop_indirect,           ADDRMD_3OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "sub",   0x4a000000, flds_3op_waop_indirect_auto_inc,  ADDRMD_3OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "sub",   0x4b000000, flds_3op_waop_indexed,            ADDRMD_3OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "sub",   0x4b000000, flds_3op_waop_direct_long,        ADDRMD_3OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "sub",   0x4b000000, flds_3op_waop_indexed_long,       ADDRMD_3OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "mulu",  0x4c000000, flds_3op_waopl_direct,            ADDRMD_3OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "mulu",  0x4d000000, flds_3op_waopl_immediate,         ADDRMD_3OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "mulu",  0x4e000000, flds_3op_waopl_indirect,          ADDRMD_3OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "mulu",  0x4e000000, flds_3op_waopl_indirect_auto_inc, ADDRMD_3OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "mulu",  0x4f000000, flds_3op_waopl_indexed,           ADDRMD_3OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "mulu",  0x4f000000, flds_3op_waopl_direct_long,       ADDRMD_3OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "mulu",  0x4f000000, flds_3op_waopl_indexed_long,      ADDRMD_3OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "andb",  0x50000000, flds_3op_baop_direct,             ADDRMD_3OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "andb",  0x51000000, flds_3op_baop_immediate,          ADDRMD_3OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "andb",  0x52000000, flds_3op_baop_indirect,           ADDRMD_3OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "andb",  0x52000000, flds_3op_baop_indirect_auto_inc,  ADDRMD_3OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "andb",  0x53000000, flds_3op_baop_indexed,            ADDRMD_3OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "andb",  0x53000000, flds_3op_baop_direct_long,        ADDRMD_3OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "andb",  0x53000000, flds_3op_baop_indexed_long,       ADDRMD_3OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "addb",  0x54000000, flds_3op_baop_direct,             ADDRMD_3OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "addb",  0x55000000, flds_3op_baop_immediate,          ADDRMD_3OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "addb",  0x56000000, flds_3op_baop_indirect,           ADDRMD_3OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "addb",  0x56000000, flds_3op_baop_indirect_auto_inc,  ADDRMD_3OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "addb",  0x57000000, flds_3op_baop_indexed,            ADDRMD_3OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "addb",  0x57000000, flds_3op_baop_direct_long,        ADDRMD_3OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "addb",  0x57000000, flds_3op_baop_indexed_long,       ADDRMD_3OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "subb",  0x58000000, flds_3op_baop_direct,             ADDRMD_3OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "subb",  0x59000000, flds_3op_baop_immediate,          ADDRMD_3OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "subb",  0x5a000000, flds_3op_baop_indirect,           ADDRMD_3OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "subb",  0x5a000000, flds_3op_baop_indirect_auto_inc,  ADDRMD_3OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "subb",  0x5b000000, flds_3op_baop_indexed,            ADDRMD_3OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "subb",  0x5b000000, flds_3op_baop_direct_long,        ADDRMD_3OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "subb",  0x5b000000, flds_3op_baop_indexed_long,       ADDRMD_3OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "mulub", 0x5c000000, flds_3op_baopw_direct,            ADDRMD_3OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "mulub", 0x5d000000, flds_3op_baopw_immediate,         ADDRMD_3OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "mulub", 0x5e000000, flds_3op_baopw_indirect,          ADDRMD_3OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "mulub", 0x5e000000, flds_3op_baopw_indirect_auto_inc, ADDRMD_3OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "mulub", 0x5f000000, flds_3op_baopw_indexed,           ADDRMD_3OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "mulub", 0x5f000000, flds_3op_baopw_direct_long,       ADDRMD_3OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "mulub", 0x5f000000, flds_3op_baopw_indexed_long,      ADDRMD_3OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "and",   0x60000000, flds_2op_waop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "and",   0x61000000, flds_2op_waop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "and",   0x62000000, flds_2op_waop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "and",   0x62000000, flds_2op_waop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "and",   0x63000000, flds_2op_waop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "and",   0x63000000, flds_2op_waop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "and",   0x63000000, flds_2op_waop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "add",   0x64000000, flds_2op_waop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "add",   0x65000000, flds_2op_waop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "add",   0x66000000, flds_2op_waop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "add",   0x66000000, flds_2op_waop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "add",   0x67000000, flds_2op_waop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "add",   0x67000000, flds_2op_waop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "add",   0x67000000, flds_2op_waop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "sub",   0x68000000, flds_2op_waop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "sub",   0x69000000, flds_2op_waop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "sub",   0x6a000000, flds_2op_waop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "sub",   0x6a000000, flds_2op_waop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "sub",   0x6b000000, flds_2op_waop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "sub",   0x6b000000, flds_2op_waop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "sub",   0x6b000000, flds_2op_waop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "mulu",  0x6c000000, flds_2op_waopl_direct,            ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "mulu",  0x6d000000, flds_2op_waopl_immediate,         ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "mulu",  0x6e000000, flds_2op_waopl_indirect,          ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "mulu",  0x6e000000, flds_2op_waopl_indirect_auto_inc, ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "mulu",  0x6f000000, flds_2op_waopl_indexed,           ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "mulu",  0x6f000000, flds_2op_waopl_direct_long,       ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "mulu",  0x6f000000, flds_2op_waopl_indexed_long,      ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "andb",  0x70000000, flds_2op_baop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "andb",  0x71000000, flds_2op_baop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "andb",  0x72000000, flds_2op_baop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "andb",  0x72000000, flds_2op_baop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "andb",  0x73000000, flds_2op_baop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "andb",  0x73000000, flds_2op_baop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "andb",  0x73000000, flds_2op_baop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "addb",  0x74000000, flds_2op_baop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "addb",  0x75000000, flds_2op_baop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "addb",  0x76000000, flds_2op_baop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "addb",  0x76000000, flds_2op_baop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "addb",  0x77000000, flds_2op_baop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "addb",  0x77000000, flds_2op_baop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "addb",  0x77000000, flds_2op_baop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "subb",  0x78000000, flds_2op_baop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "subb",  0x79000000, flds_2op_baop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "subb",  0x7a000000, flds_2op_baop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "subb",  0x7a000000, flds_2op_baop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "subb",  0x7b000000, flds_2op_baop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "subb",  0x7b000000, flds_2op_baop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "subb",  0x7b000000, flds_2op_baop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "mulub", 0x7c000000, flds_2op_baopw_direct,            ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "mulub", 0x7d000000, flds_2op_baopw_immediate,         ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "mulub", 0x7e000000, flds_2op_baopw_indirect,          ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "mulub", 0x7e000000, flds_2op_baopw_indirect_auto_inc, ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "mulub", 0x7f000000, flds_2op_baopw_indexed,           ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "mulub", 0x7f000000, flds_2op_baopw_direct_long,       ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "mulub", 0x7f000000, flds_2op_baopw_indexed_long,      ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "or",    0x80000000, flds_2op_waop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "or",    0x81000000, flds_2op_waop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "or",    0x82000000, flds_2op_waop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "or",    0x82000000, flds_2op_waop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "or",    0x83000000, flds_2op_waop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "or",    0x83000000, flds_2op_waop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "or",    0x83000000, flds_2op_waop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "xor",   0x84000000, flds_2op_waop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "xor",   0x85000000, flds_2op_waop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "xor",   0x86000000, flds_2op_waop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "xor",   0x86000000, flds_2op_waop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "xor",   0x87000000, flds_2op_waop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "xor",   0x87000000, flds_2op_waop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "xor",   0x87000000, flds_2op_waop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "cmp",   0x88000000, flds_2op_waop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "cmp",   0x89000000, flds_2op_waop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "cmp",   0x8a000000, flds_2op_waop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "cmp",   0x8a000000, flds_2op_waop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "cmp",   0x8b000000, flds_2op_waop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "cmp",   0x8b000000, flds_2op_waop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "cmp",   0x8b000000, flds_2op_waop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "divu",  0x8c000000, flds_2op_waopl_direct,            ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "divu",  0x8d000000, flds_2op_waopl_immediate,         ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "divu",  0x8e000000, flds_2op_waopl_indirect,          ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "divu",  0x8e000000, flds_2op_waopl_indirect_auto_inc, ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "divu",  0x8f000000, flds_2op_waopl_indexed,           ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "divu",  0x8f000000, flds_2op_waopl_direct_long,       ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "divu",  0x8f000000, flds_2op_waopl_indexed_long,      ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "orb",   0x90000000, flds_2op_baop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "orb",   0x91000000, flds_2op_baop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "orb",   0x92000000, flds_2op_baop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "orb",   0x92000000, flds_2op_baop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "orb",   0x93000000, flds_2op_baop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "orb",   0x93000000, flds_2op_baop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "orb",   0x93000000, flds_2op_baop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "xorb",  0x94000000, flds_2op_baop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "xorb",  0x95000000, flds_2op_baop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "xorb",  0x96000000, flds_2op_baop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "xorb",  0x96000000, flds_2op_baop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "xorb",  0x97000000, flds_2op_baop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "xorb",  0x97000000, flds_2op_baop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "xorb",  0x97000000, flds_2op_baop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "cmpb",  0x98000000, flds_2op_baop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "cmpb",  0x99000000, flds_2op_baop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "cmpb",  0x9a000000, flds_2op_baop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "cmpb",  0x9a000000, flds_2op_baop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "cmpb",  0x9b000000, flds_2op_baop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "cmpb",  0x9b000000, flds_2op_baop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "cmpb",  0x9b000000, flds_2op_baop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "divub", 0x9c000000, flds_2op_baopw_direct,            ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "divub", 0x9d000000, flds_2op_baopw_immediate,         ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "divub", 0x9e000000, flds_2op_baopw_indirect,          ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "divub", 0x9e000000, flds_2op_baopw_indirect_auto_inc, ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "divub", 0x9f000000, flds_2op_baopw_indexed,           ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "divub", 0x9f000000, flds_2op_baopw_direct_long,       ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "divub", 0x9f000000, flds_2op_baopw_indexed_long,      ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "ld",    0xa0000000, flds_2op_waop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "ld",    0xa1000000, flds_2op_waop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "ld",    0xa2000000, flds_2op_waop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "ld",    0xa2000000, flds_2op_waop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "ld",    0xa3000000, flds_2op_waop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "ld",    0xa3000000, flds_2op_waop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "ld",    0xa3000000, flds_2op_waop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "addc",  0xa4000000, flds_2op_waop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "addc",  0xa5000000, flds_2op_waop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "addc",  0xa6000000, flds_2op_waop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "addc",  0xa6000000, flds_2op_waop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "addc",  0xa7000000, flds_2op_waop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "addc",  0xa7000000, flds_2op_waop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "addc",  0xa7000000, flds_2op_waop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "subc",  0xa8000000, flds_2op_waop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "subc",  0xa9000000, flds_2op_waop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "subc",  0xaa000000, flds_2op_waop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "subc",  0xaa000000, flds_2op_waop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "subc",  0xab000000, flds_2op_waop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "subc",  0xab000000, flds_2op_waop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "subc",  0xab000000, flds_2op_waop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "ldbze", 0xac000000, flds_2op_baopw_direct,            ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "ldbze", 0xad000000, flds_2op_baopw_immediate,         ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "ldbze", 0xae000000, flds_2op_baopw_indirect,          ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "ldbze", 0xae000000, flds_2op_baopw_indirect_auto_inc, ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "ldbze", 0xaf000000, flds_2op_baopw_indexed,           ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "ldbze", 0xaf000000, flds_2op_baopw_direct_long,       ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "ldbze", 0xaf000000, flds_2op_baopw_indexed_long,      ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "ldb",   0xb0000000, flds_2op_baop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "ldb",   0xb1000000, flds_2op_baop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "ldb",   0xb2000000, flds_2op_baop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "ldb",   0xb2000000, flds_2op_baop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "ldb",   0xb3000000, flds_2op_baop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "ldb",   0xb3000000, flds_2op_baop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "ldb",   0xb3000000, flds_2op_baop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "addcb", 0xb4000000, flds_2op_baop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "addcb", 0xb5000000, flds_2op_baop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "addcb", 0xb6000000, flds_2op_baop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "addcb", 0xb6000000, flds_2op_baop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "addcb", 0xb7000000, flds_2op_baop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "addcb", 0xb7000000, flds_2op_baop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "addcb", 0xb7000000, flds_2op_baop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "subcb", 0xb8000000, flds_2op_baop_direct,             ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "subcb", 0xb9000000, flds_2op_baop_immediate,          ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "subcb", 0xba000000, flds_2op_baop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "subcb", 0xba000000, flds_2op_baop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "subcb", 0xbb000000, flds_2op_baop_indexed,            ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "subcb", 0xbb000000, flds_2op_baop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "subcb", 0xbb000000, flds_2op_baop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "ldbse", 0xbc000000, flds_2op_baopw_direct,            ADDRMD_2OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "ldbse", 0xbd000000, flds_2op_baopw_immediate,         ADDRMD_2OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "ldbse", 0xbe000000, flds_2op_baopw_indirect,          ADDRMD_2OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "ldbse", 0xbe000000, flds_2op_baopw_indirect_auto_inc, ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "ldbse", 0xbf000000, flds_2op_baopw_indexed,           ADDRMD_2OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "ldbse", 0xbf000000, flds_2op_baopw_direct_long,       ADDRMD_2OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "ldbse", 0xbf000000, flds_2op_baopw_indexed_long,      ADDRMD_2OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "st",    0xc0000000, flds_2op_waop_direct,             ADDRMD_2OP_DIRECT,            TGT_WRITE ),                                  \
    INSTRUCTION_INST( NULL,    0xc1000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "st",    0xc2000000, flds_2op_waop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_WRITE ),                                  \
    INSTRUCTION_INST( "st",    0xc2000000, flds_2op_waop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_WRITE ),                                  \
    INSTRUCTION_INST( "st",    0xc3000000, flds_2op_waop_indexed,            ADDRMD_2OP_INDEXED,           TGT_WRITE ),                                  \
    INSTRUCTION_INST( "st",    0xc3000000, flds_2op_waop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_WRITE ),                                  \
    INSTRUCTION_INST( "st",    0xc3000000, flds_2op_waop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_WRITE ),                                  \
    INSTRUCTION_INST( "stb",   0xc4000000, flds_2op_baop_direct,             ADDRMD_2OP_DIRECT,            TGT_WRITE ),                                  \
    INSTRUCTION_INST( NULL,    0xc5000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "stb",   0xc6000000, flds_2op_baop_indirect,           ADDRMD_2OP_INDIRECT,          TGT_WRITE ),                                  \
    INSTRUCTION_INST( "stb",   0xc6000000, flds_2op_baop_indirect_auto_inc,  ADDRMD_2OP_INDIRECT_AUTO_INC, TGT_WRITE ),                                  \
    INSTRUCTION_INST( "stb",   0xc7000000, flds_2op_baop_indexed,            ADDRMD_2OP_INDEXED,           TGT_WRITE ),                                  \
    INSTRUCTION_INST( "stb",   0xc7000000, flds_2op_baop_direct_long,        ADDRMD_2OP_DIRECT_LONG,       TGT_WRITE ),                                  \
    INSTRUCTION_INST( "stb",   0xc7000000, flds_2op_baop_indexed_long,       ADDRMD_2OP_INDEXED_LONG,      TGT_WRITE ),                                  \
    INSTRUCTION_INST( "push",  0xc8000000, flds_1op_waop_direct,             ADDRMD_1OP_DIRECT,            TGT_READ ),                                   \
    INSTRUCTION_INST( "push",  0xc9000000, flds_1op_waop_immediate,          ADDRMD_1OP_IMMEDIATE,         TGT_READ ),                                   \
    INSTRUCTION_INST( "push",  0xca000000, flds_1op_waop_indirect,           ADDRMD_1OP_INDIRECT,          TGT_READ ),                                   \
    INSTRUCTION_INST( "push",  0xca000000, flds_1op_waop_indirect_auto_inc,  ADDRMD_1OP_INDIRECT_AUTO_INC, TGT_READ ),                                   \
    INSTRUCTION_INST( "push",  0xcb000000, flds_1op_waop_indexed,            ADDRMD_1OP_INDEXED,           TGT_READ ),                                   \
    INSTRUCTION_INST( "push",  0xcb000000, flds_1op_waop_direct_long,        ADDRMD_1OP_DIRECT_LONG,       TGT_READ ),                                   \
    INSTRUCTION_INST( "push",  0xcb000000, flds_1op_waop_indexed_long,       ADDRMD_1OP_INDEXED_LONG,      TGT_READ ),                                   \
    INSTRUCTION_INST( "pop",   0xcc000000, flds_1op_waop_direct,             ADDRMD_1OP_DIRECT,            TGT_WRITE ),                                  \
    INSTRUCTION_INST( NULL,    0xcd000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "pop",   0xce000000, flds_1op_waop_indirect,           ADDRMD_1OP_INDIRECT,          TGT_WRITE ),                                  \
    INSTRUCTION_INST( "pop",   0xce000000, flds_1op_waop_indirect_auto_inc,  ADDRMD_1OP_INDIRECT_AUTO_INC, TGT_WRITE ),                                  \
    INSTRUCTION_INST( "pop",   0xcf000000, flds_1op_waop_indexed,            ADDRMD_1OP_INDEXED,           TGT_WRITE ),                                  \
    INSTRUCTION_INST( "pop",   0xcf000000, flds_1op_waop_direct_long,        ADDRMD_1OP_DIRECT_LONG,       TGT_WRITE ),                                  \
    INSTRUCTION_INST( "pop",   0xcf000000, flds_1op_waop_indexed_long,       ADDRMD_1OP_INDEXED_LONG,      TGT_WRITE ),                                  \
    INSTRUCTION_INST( "jnst",  0xd0000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jnh",   0xd1000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jgt",   0xd2000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jnc",   0xd3000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jnvt",  0xd4000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jnv",   0xd5000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jge",   0xd6000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jne",   0xd7000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jst",   0xd8000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jh",    0xd9000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jle",   0xda000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jc",    0xdb000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jvt",   0xdc000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jv",    0xdd000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "jlt",   0xde000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "je",    0xdf000000, flds_jmp,                         ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( "djnz",  0xe0000000, flds_djnz,                        ADDRMD_2OP_DIRECT_LONG,       TGT_EXECUTION_JUMP ),                         \
    INSTRUCTION_INST( NULL,    0xe1000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xe2000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xe3000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xe4000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xe5000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xe6000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "ljmp",  0xe7000000, flds_lcall_ljmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_BARRIER ), \
    INSTRUCTION_INST( NULL,    0xe8000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xe9000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xea000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xeb000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xec000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xed000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xee000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "lcall", 0xef000000, flds_lcall_ljmp,                  ADDRMD_1OP_DIRECT_LONG,       TGT_EXECUTION_JUMP | TGT_EXECUTION_CALL ),    \
    INSTRUCTION_INST( "ret",   0xf0000000, flds_intrinsic,                   ADDRMD_INTRINSIC,             TGT_EXECUTION_BARRIER ),                      \
    INSTRUCTION_INST( "reti",  0xf1000000, flds_intrinsic,                   ADDRMD_INTRINSIC,             TGT_EXECUTION_BARRIER ),                      \
    INSTRUCTION_INST( "pushf", 0xf2000000, flds_intrinsic,                   ADDRMD_INTRINSIC,             0 ),                                          \
    INSTRUCTION_INST( "popf",  0xf3000000, flds_intrinsic,                   ADDRMD_INTRINSIC,             0 ),                                          \
    INSTRUCTION_INST( NULL,    0xf4000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xf5000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xf6000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "trap",  0xf7000000, flds_intrinsic,                   ADDRMD_INTRINSIC,             0 ),                                          \
    INSTRUCTION_INST( "clrc",  0xf8000000, flds_intrinsic,                   ADDRMD_INTRINSIC,             0 ),                                          \
    INSTRUCTION_INST( "setc",  0xf9000000, flds_intrinsic,                   ADDRMD_INTRINSIC,             0 ),                                          \
    INSTRUCTION_INST( "di",    0xfa000000, flds_intrinsic,                   ADDRMD_INTRINSIC,             0 ),                                          \
    INSTRUCTION_INST( "ei",    0xfb000000, flds_intrinsic,                   ADDRMD_INTRINSIC,             0 ),                                          \
    INSTRUCTION_INST( "clrvt", 0xfc000000, flds_intrinsic,                   ADDRMD_INTRINSIC,             0 ),                                          \
    INSTRUCTION_INST( NULL,    0xfd000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( NULL,    0xfe000000, NULL,                             0,                            TGT_INVALID ),                                \
    INSTRUCTION_INST( "nop",   0xff000000, flds_intrinsic,                   ADDRMD_INTRINSIC,             0 ),
